### ISSUE TITLE
Make `AssumeSortedStarts` easier to use

### ISSUE THREAD

**Issue by bonsairobo** [CarlKCarlK/range-set-blaze#15]
I'm trying to replace my own range set implementation with this crate, and something I need to do often is merge sorted ranges that are not necessarily disjoint. It seems like `UnionIter` and `AssumeSortedStarts` are the right tools for this. There are a few small changes that I think would improve this use case:

1. Document `SortedStarts` and `AssumeSortedStarts`. I find it odd that these have `#[doc(hidden)]`. It was not obvious that such APIs existed until I snooped around the code a bit.
2. Add a constructor for `AssumeSortedStarts` which takes `I: IntoIterator`. Right now it only takes `I: Iterator`, so I have to manually call `into_iter()` when I use it.
3. Maybe add an extension trait so I can do something like: `[0..1, 0..2].assume_sorted()` instead of `AssumeSortedStarts::new([0..1, 0..2])`.

I can probably make a PR with these changes if you like.

**Comment by CarlKCarlK** [comment]
Duncan,

Thanks for looking at using RangeSetBlaze!

These seem like great changes. I welcome your PR.

I wonder if we should also create a new constructor for RangeSetBlaze, itself, something like `from_sorted_starts`? That way, people who have sorted starts would not need to learn about `UnionIter`.

-- Carl
p.s. I'm working on [adding `RangeMapBlaze`,](https://github.com/CarlKCarlK/range-set-blaze/tree/feb24) a map. I leave on a 1-week vacation in a few days.

**Comment by bonsairobo** [comment]
> I wonder if we should also create a new constructor for RangeSetBlaze, itself, something like from_sorted_starts? That way, people who have sorted starts would not need to learn about UnionIter.

That could be nice! I don't personally use `RangeSetBlaze`, but maybe I would if it were `serde`-serializable. Actually, if we had a `RangeSetBlaze::into_inner` that returned the `BTreeMap`, that would make it trivially serializable.

**Comment by CarlKCarlK** [comment]
Duncan, it's published! Thanks for your contribution.
https://crates.io/crates/range-set-blaze

The only change I made was to remove one `.into_iter()` that Clippy said wasn't needed. I appreciate that you cleaned up the many now-not-needed `.into_iters()` in the tests. Also, replacing `RangeSetBlaze` with `Self` was good.

Finally, thanks for even noticing the `SortedDisjoint`/`SortedStarts` features. It's my favorite part of the code but is hidden from most users.
