### ISSUE TITLE
`no_std` support

### ISSUE THREAD

**Issue by Oppen** [CarlKCarlK/range-set-blaze#7]
It would be very useful for this crate to be usable in `no_std` environments. At a glance, the only hard requirement I see in the crate is really `alloc`, so it could be more lax about requiring the whole `std` support. That would allow uses in bare-metal and wasm.

**Comment by CarlKCarlK** [comment]
Great suggestion! I'm looking into it. WASM would be especially fun.

I recently removed support for 16-bit architectures. I suppose I should put that back in if people might want to run this on a microcontroller.

**Comment by CarlKCarlK** [comment]
I have a branch working in WASM now. That mostly required moving crate 'rand' to dev-dependencies.

I tried getting no_std working, but it uses itertools extensively - including .tee() and .kmerge_by() which are only available with itertools std ([details](https://docs.rs/itertools/latest/itertools/#crate-features)). [I'm testing with [QEMU as explained by the Rust Embedded Book](https://docs.rust-embedded.org/book/start/qemu.html).] If anyone would really like it on no_std, let me know what features you need. I may keep looking if I can remove some features and make it no_std.

I assume making it WASM-compatible is useful even if it doesn't work on bare metal, yes?

**Comment by Oppen** [comment]
> I assume making it WASM-compatible is useful even if it doesn't work on bare metal, yes?

Yes! I mentioned embedded mostly because it's an interesting use case, but WASM is actually something that I could use right now :)

**Comment by CarlKCarlK** [comment]
The crate now supports no_std for both WASM and embedded.
I also wrote an article about how to port packages to make them no_std.
