### ISSUE TITLE
consider addinf roaring bitmap to benchmarks 

### ISSUE THREAD

**Issue by msalib** [CarlKCarlK/range-set-blaze#8]
https://docs.rs/roaring/latest/roaring/

**Comment by CarlKCarlK** [comment]
The [RoaringBitmap](https://docs.rs/roaring/latest/roaring/bitmap/struct.RoaringBitmap.html) looks very cool! Thanks for suggesting this.

I'm very interested in testing it with the model of 'clumpiness' used by the benchmark. (Described in [Benchmark](https://github.com/CarlKCarlK/range-set-blaze/blob/main/docs/bench.md) #2)

I hope to do this "soon", but don't have a timetable.

**Comment by CarlKCarlK** [comment]
The update is complete. Thanks again for the suggestion!
https://github.com/CarlKCarlK/range-set-blaze/blob/main/docs/bench.md

In general, Roaring is much better than RangeSetBlaze when the u32s are uniform. RangeSetBlaze does much better than Roaring on clumpy integers. Both offer similar interfaces. If you're not sure which is best for your application, you can easily swap between them and see.
